// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"github.com/krishpatel09/streaming-platform/services/auth-service/internal/api/handler"
	"github.com/krishpatel09/streaming-platform/services/auth-service/internal/api/router"
	"github.com/krishpatel09/streaming-platform/services/auth-service/internal/config"
	"github.com/krishpatel09/streaming-platform/services/auth-service/internal/db"
	"github.com/krishpatel09/streaming-platform/services/auth-service/internal/repository"
	"github.com/krishpatel09/streaming-platform/services/auth-service/internal/usecase"
)

// Injectors from wire.go:

func Initialize(cfg config.PostgresConfig, redisCfg config.RedisConfig) (*gin.Engine, error) {
	gormDB, err := db.ConnectPostgres(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	client, err := db.ConnectRedis(redisCfg)
	if err != nil {
		return nil, err
	}
	redisRepository := repository.NewRedisRepository(client)
	refreshTokenRepository := repository.NewRefreshTokenRepository(gormDB)
	emailSender := ProvideEmailSender()
	string2 := ProvideSecretKey()
	authUseCase := usecase.NewAuthUseCase(userRepository, redisRepository, refreshTokenRepository, emailSender, string2)
	authHandler := handler.NewAuthHandler(authUseCase)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	engine := router.NewRouter(authHandler, userHandler)
	return engine, nil
}
